@ParametersAreNonnullByDefault
@FieldsAndMethodsAreNonnullByDefault
package com.ultramega.playershells.packet.s2c;

import com.ultramega.playershells.utils.FieldsAndMethodsAreNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
