@ParametersAreNonnullByDefault
@FieldsAndMethodsAreNonnullByDefault
package com.ultramega.playershells.network;

import com.ultramega.playershells.utils.FieldsAndMethodsAreNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
